package IOT.coldchain.application.dto.command;

import IOT.coldchain.domain.enums.CommandType;

/**
 * COMMAND — IssueDriverCommandCommand
 *
 * Represents an Admin's intent to issue an operational order to the assigned
 * driver of a truck.
 *
 * Handled by: IssueDriverCommandUseCase
 * Domain method called: truck.issueDriverCommand(commandId, adminId, type, customMessage)
 * Business rules enforced by domain:
 *   - Truck must have an assigned driver.
 *   - STOP command requires the truck to be IN_TRANSIT (Rule E2).
 *   - CUSTOM type requires a non-blank customMessage (Rule E1).
 *   - A new commandId UUID is generated by the handler before calling the domain.
 *   - A DriverCommandIssuedEvent is raised automatically by the domain.
 *
 * @param truckId        the truck whose driver should receive the command
 * @param adminId        the ID of the AdminUser issuing the command
 * @param commandType    the type of operation being ordered
 * @param customMessage  free-text instruction (required only for CUSTOM type, else null)
 */
public record IssueDriverCommandCommand(
        String truckId,
        String adminId,
        CommandType commandType,
        String customMessage
) {}